<?php
include('./inc/css.php');
include('./inc/header.php');
include('./intro.php');
include('./register.php');
include('./ourclients.php');
include('./team.php');
include('./gallery.php');
include('./learnandearn.php');
include('./technology.php');
include('./contectus.php');
include('./aboutus.php');
include('./faqsection.php');
include('./footer.php');
include('./inc/footer.php');
