<?php
include('./register.php');
include('./ourclients.php');
include('./team.php');
include('./gallery.php');
include('./faqsection.php');
include('./learnandearn.php');
include('./technology.php');
include('./contectus.php');
include('./aboutus.php');
?>